# Configuration for Nightmare - ASCII Horror Game

# Graphics settings
graphics:
  width: 1280           # Window width
  height: 720           # Window height
  fullscreen: false     # Fullscreen mode
  vsync: true           # Vertical sync
  framerate: 60         # Frame rate limit
  display_mode: opengl  # Rendering mode (opengl, ascii)

# Audio settings
audio:
  enabled: true         # Enable audio
  volume: 0.8           # Volume (0.0-1.0)
  enable_mic: true      # Enable microphone
  mic_sensitivity: 0.7  # Microphone sensitivity
  effect_volume: 0.7    # Effect volume
  ambient_volume: 0.5   # Ambient volume
  reverb_amount: 0.6    # Reverb amount
  bass_boost: 0.3       # Bass boost

# Raytracer settings
raytracer:
  width: 160            # Raytracer resolution width
  height: 90            # Raytracer resolution height
  num_threads: 4        # Number of threads for raytracing
  max_bounces: 1        # Max ray bounces
  shadows_enabled: true # Enable shadows
  fog_enabled: true     # Enable fog

# Renderer settings
renderer:
  width: 160            # ASCII grid width
  height: 90            # ASCII grid height
  charset: " .:-=+*#%@" # ASCII character set from dark to light
  color_mode: color     # Color mode (mono, grayscale, color)
  glitch_amount: 0.0    # Default glitch amount

# Procedural generation settings
procedural:
  terrain_size: 256     # Terrain size
  tree_density: 6.0     # Tree density
  rock_density: 4.0     # Rock density
  strange_density: 0.5  # Strange object density
  detail_level: 4       # Detail level
  seed: 0               # Seed (0 = random)
  biome: dark_forest    # Biome type

# AI settings
ai:
  enabled: true         # Enable AI
  difficulty: 0.5       # Difficulty (0.0-1.0)
  adaptation_rate: 0.3  # Adaptation rate
  mic_enabled: true     # Enable microphone for AI
  behavior_analysis: true # Analyze player behavior
  fear_threshold: 0.7   # Fear threshold

# Mod settings
mods:
  enabled: true         # Enable mods
  mods_folder: mods     # Mods folder
  enabled_mods: []      # Enabled mods list

# Player settings
player:
  move_speed: 2.0       # Movement speed
  turn_speed: 2.0       # Turn speed
  collision_radius: 0.5 # Collision radius
  height: 1.7           # Player height
  camera_height: 1.6    # Camera height
  fov: 75               # Field of view (degrees)

# Atmosphere settings
atmosphere:
  fear_base: 0.4        # Base fear level
  darkness_intensity: 0.7 # Darkness intensity at night
  fog_density: 0.5      # Fog density
  day_cycle_minutes: 15 # Day/night cycle length (minutes)